language: perl

sudo: false
dist: trusty

install:
  - perlbrew list
  - cpanm -n App::af Sort::Versions
  - af missing | cpanm -n
  - autoconf --version
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - dzil test -v

env:
  global:
    - ALIEN_BASE_NO_ABMB=1
    - PATH=$HOME/mytravis/bin:$PATH
  matrix:
    - ALIEN_INSTALL_TYPE=share
    - ALIEN_INSTALL_TYPE=system
